# Generated by Django 2.1.1 on 2018-09-28 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('actions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FollowCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Choice')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Condition')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playthrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('is_secret', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Game')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('playtrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Playthrough')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Stat')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=10000)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Game')),
            ],
        ),
        migrations.CreateModel(
            name='StoryChoiceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Choice')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Story')),
            ],
        ),
        migrations.CreateModel(
            name='TextVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_secret', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Textvars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
                ('playtrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Playthrough')),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.TextVariable')),
            ],
        ),
        migrations.AddField(
            model_name='playthrough',
            name='story_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Story'),
        ),
        migrations.AddField(
            model_name='playthrough',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='first_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='flow.Story'),
        ),
        migrations.AddField(
            model_name='followcondition',
            name='follow_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Story'),
        ),
        migrations.AddField(
            model_name='editors',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Game'),
        ),
        migrations.AddField(
            model_name='editors',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='condition_to_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Condition'),
        ),
    ]
