# Generated by Django 2.1.1 on 2018-10-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_auto_20181003_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='editor_panel_x',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='editor_panel_y',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
